# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    name: Test
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch git submodules (C++ core)

      # Set up Swift compiler environment
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      # Build using our custom script (uses Apple Clang)
      - name: Build LocalizeAR
        run: |
          chmod +x build.sh
          ./build.sh
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++

      # Run tests (when enabled)
      - name: Run Tests
        run: ./build.sh test
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
        continue-on-error: true  # Don't fail workflow if tests aren't implemented yet

      # Optional: Build for iOS (using xcodebuild)
      # - name: Build for iOS
      #   run: xcodebuild -scheme LocalizeAR clean build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15'
